services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: sorix_crm_dev_app
    volumes:
      - ./src:/var/www
    networks:
      - net_eduranga
    depends_on:
      - mysql
      - redis
    env_file:
      -  .env.docker
    environment:
      APP_NAME: "new-UCZE"
      APP_ENV: local
      HORIZON_ENV: local
      
    extra_hosts:
      - "dam.wsip.pl:172.17.0.62"
      - "zasoby.wsip.pl:77.79.199.7"
      - "uczetst.zasoby.wsip.pl:77.79.199.7"

  webserver:
    image: nginx:alpine
    container_name: sorix_crm_dev_nginx
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    ports:
      - "8084:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - net_eduranga
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: sorix_crm_dev_mysql
    env_file:
      -  .env.docker
    command: --sort_buffer_size=64M
    ports:
      - "3308:3306"
    volumes:
      - dbdata_dev:/var/lib/mysql
    networks:
      - net_eduranga

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    env_file:
      -  .env.docker
    ports:
        - 8089:80
    networks:
        - net_eduranga

  redis:
    image: redis:alpine
    container_name: sorix_crm_dev_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata_dev:/data
    networks:
      - net_eduranga

  meilisearch:
    image: getmeili/meilisearch:v1.14.0
    container_name: sorix_crm_dev_meilisearch
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-masterKey}
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - net_eduranga

networks:
  net_eduranga:
    name: net_eduranga
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.7.0/24

volumes:
  dbdata_dev:
    name: new_crm_dev_dbdata
  redisdata_dev:
    name: new_crm_dev_redisdata
  meilisearch_data:
    name: new_crm_dev_meilisearch_data